#!/usr/bin/env bash
#Install and configure HAProxy

sudo apt update
sudo apt install haproxy -y
haproxy=/etc/default/haproxy
echo "ENABLED=1" | sudo tee -a $haproxy

path=/etc/haproxy/haproxy.cfg
config=\
"
frontend manage_entry
	  bind *:80
	  default_backend my_web_servers
backend my_web_servers
	balance static-rr
	server 6315-web-01 34.224.15.230:80 check
	server 6315-web-02 18.234.105.64:80 check
"

echo "$config" | sudo tee -a "$path"
sudo systemctl restart haproxy.service
